# Generated by Django 6.0.6 on 2026-06-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
